[aws]
disabled = true

[battery]
disabled = true
# full_symbol = ""
# charging_symbol = ""
# discharging_symbol = ""

# [[battery.display]]
# threshold = 25
# style = "bold red"

# [[battery.display]]
# threshold = 50
# style = "bold yellow"

[dart]
symbol = " "

[directory]
truncation_symbol = ".../"
# fish_style_pwd_dir_length = 2

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[status]
disabled = false
symbol = " "
format = "\\[[$symbol$status]($style)\\] "

[swift]
symbol = "ﯣ "

[terraform]
format = "[tf $version]($style)"

[time]
disabled = false
format = " \\[$time\\] "
